/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as ApiBlogUploadRouteImport } from './routes/api/blog/upload'
import { Route as ApiBlogPostsRouteImport } from './routes/api/blog/posts'
import { Route as ApiBlogNewRouteImport } from './routes/api/blog/new'
import { Route as ApiBlogSlugRouteImport } from './routes/api/blog/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlogPostsSlugRouteImport } from './routes/api/blog/posts/$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogUploadRoute = ApiBlogUploadRouteImport.update({
  id: '/api/blog/upload',
  path: '/api/blog/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogPostsRoute = ApiBlogPostsRouteImport.update({
  id: '/api/blog/posts',
  path: '/api/blog/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogNewRoute = ApiBlogNewRouteImport.update({
  id: '/api/blog/new',
  path: '/api/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSlugRoute = ApiBlogSlugRouteImport.update({
  id: '/api/blog/$slug',
  path: '/api/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogPostsSlugRoute = ApiBlogPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/blog/new': typeof ApiBlogNewRoute
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/blog/new': typeof ApiBlogNewRoute
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/blog/new': typeof ApiBlogNewRoute
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/upload': typeof ApiBlogUploadRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/health'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/blog/new'
    | '/api/blog/posts'
    | '/api/blog/upload'
    | '/api/blog/'
    | '/api/blog/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/health'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/blog/new'
    | '/api/blog/posts'
    | '/api/blog/upload'
    | '/api/blog'
    | '/api/blog/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/health'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/blog/new'
    | '/api/blog/posts'
    | '/api/blog/upload'
    | '/api/blog/'
    | '/api/blog/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogSlugRoute: typeof ApiBlogSlugRoute
  ApiBlogNewRoute: typeof ApiBlogNewRoute
  ApiBlogPostsRoute: typeof ApiBlogPostsRouteWithChildren
  ApiBlogUploadRoute: typeof ApiBlogUploadRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/upload': {
      id: '/api/blog/upload'
      path: '/api/blog/upload'
      fullPath: '/api/blog/upload'
      preLoaderRoute: typeof ApiBlogUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/posts': {
      id: '/api/blog/posts'
      path: '/api/blog/posts'
      fullPath: '/api/blog/posts'
      preLoaderRoute: typeof ApiBlogPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/new': {
      id: '/api/blog/new'
      path: '/api/blog/new'
      fullPath: '/api/blog/new'
      preLoaderRoute: typeof ApiBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$slug': {
      id: '/api/blog/$slug'
      path: '/api/blog/$slug'
      fullPath: '/api/blog/$slug'
      preLoaderRoute: typeof ApiBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/posts/$slug': {
      id: '/api/blog/posts/$slug'
      path: '/$slug'
      fullPath: '/api/blog/posts/$slug'
      preLoaderRoute: typeof ApiBlogPostsSlugRouteImport
      parentRoute: typeof ApiBlogPostsRoute
    }
  }
}

interface ApiBlogPostsRouteChildren {
  ApiBlogPostsSlugRoute: typeof ApiBlogPostsSlugRoute
}

const ApiBlogPostsRouteChildren: ApiBlogPostsRouteChildren = {
  ApiBlogPostsSlugRoute: ApiBlogPostsSlugRoute,
}

const ApiBlogPostsRouteWithChildren = ApiBlogPostsRoute._addFileChildren(
  ApiBlogPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogSlugRoute: ApiBlogSlugRoute,
  ApiBlogNewRoute: ApiBlogNewRoute,
  ApiBlogPostsRoute: ApiBlogPostsRouteWithChildren,
  ApiBlogUploadRoute: ApiBlogUploadRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
